name: pipeline
on:
  push:
    branches:
      "master"
    jobs:
      build:
        name: fashion-blog-CI
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v3

          - name: setup java
            uses: actions/setup-java@v3
            with:
            java-version: 11
            distribution: 'adopt'

          - name: setup maven
            uses: stCarolas/setup-maven@4.4
            with:
              maven-version: 3.8.2
            -name: run compile
            run: mvn clean install

          - name: Build and push Docker image
            uses: mr-smithers-excellent/docker-build-push@v5
            with:
              image: fashion-blog-app-v1
              tags: $BUILD_NUMBER
              registry: docker.io
              dockerfile: Dockerfile
              username: ${{ secret.DOCKER_USERNAME }}
              password: ${{ secret.DOCKER_HUB_ACCESS_TOKEN }}